# Generated by Django 3.0.7 on 2020-07-06 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200706_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
